### ISSUE TITLE
Error while using

### ISSUE THREAD

**Issue by garganubhav** [Zheng-Chong/FashionMatrix#4]
Hi, I am getting this error in server.log - 
Traceback (most recent call last):
  File "/home/anubhgar/fashmatrix/FashionMatrix/server.py", line 114, in <module>
    model_cn = MultiControlNet(controlnet_folder=os.path.join(args.checkpoints, 'ControlNet'), device="cuda")
  File "/home/anubhgar/fashmatrix/FashionMatrix/models/vfm.py", line 104, in __init__
    self.pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
  File "/home/anubhgar/fashmatrix/FashionMatrix/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 1095, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/anubhgar/fashmatrix/FashionMatrix/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 470, in load_sub_model
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "/home/anubhgar/anaconda3/envs/fashionmatrix/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2269, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/anubhgar/anaconda3/envs/fashionmatrix/lib/python3.9/site-packages/transformers/configuration_utils.py", line 546, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/anubhgar/anaconda3/envs/fashionmatrix/lib/python3.9/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/anubhgar/anaconda3/envs/fashionmatrix/lib/python3.9/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/anubhgar/anaconda3/envs/fashionmatrix/lib/python3.9/site-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: ./checkpoints/realisticVisionV50_v50VAE does not appear to have a file named config.json. Checkout 'https://huggingface.co/./checkpoints/realisticVisionV50_v50VAE/None' for available files.

**Comment by Zheng-Chong** [comment]
We have released a new version 2.0, which uses less base model (thus requires less video memory and runs faster), please follow the installation guide to deploy, hope it can solve your problem.
